<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.81.0" />


<title>How much does recruiting impact success and vice versa in college basketball? - Gavin Struve&#39;s Github Site</title>
<meta property="og:title" content="How much does recruiting impact success and vice versa in college basketball? - Gavin Struve&#39;s Github Site">




  










<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/%3cnil%3e"
         width=""
         height=""
         alt="">
  </a>

  <ul class="nav-links">
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">13 min read</span>
    

    <h1 class="article-title">How much does recruiting impact success and vice versa in college basketball?</h1>

    
    <span class="article-date">2021-04-25</span>
    

    <div class="article-content">
      
<script src="http://gavinstruve.github.io/post/2021/04/25/how-much-does-recruiting-impact-success-and-vice-versa-in-college-basketball/index_files/header-attrs/header-attrs.js"></script>


<p>It’s no secret that recruiting is an integral part of building a competent and competitive college basketball program. The best teams are often among the best recruiters, in theory good recruiting is rewarded with wins, and success is rewarded with signing top recruits. However, this is not always the case. There are outliers, teams that get average recruits but finish among the top teams and recruiters on the court, as well as teams that recruit better than almost anyone but underperform relative to talent.</p>
<p>In a year with more upsets than ever in the NCAA Tournament and the bluebloods facing early exits or not even making the tournament at all, it’s worth examining how significant of an impact recruiting has on on-court success.</p>
<pre class="r"><code>library(tidyverse)
library(gt)
library(ggrepel)
library(ggalt)
library(ggplot2)</code></pre>
<pre class="r"><code>recruitingtables &lt;- read_csv(&quot;recruittables.csv&quot;)
thisyrrecruits &lt;- read_csv(&quot;2021recruittables.csv&quot;)</code></pre>
<p>I’m going to use two datasets, the first we’ll name recruitingtables, it features every team from the six power conferences and a few of the top mid-majors from the last five years. The dataset contains the total number of commits for each team, how many four and five-stars they signed, average recruiting ranking and points as well as their win-percentage over the last five years, their average kenpom rating during that time and their tournament appearances and wins. All of this data was gathered manually from Sports Reference and 247Sports, the latter of which gives the best picture of consensus of recruiting services thanks to its composite ranking which takes in several of the top recruiting service rankings.</p>
<pre class="r"><code>toprecruitteams &lt;- recruitingtables %&gt;% top_n(10, wt = avgrecruitingpts) </code></pre>
<p>Let’s first take a look at which teams have recruited the best over the last five seasons. We’re going to order the top recruiting teams by average recruiting points from 247Sports’ metric. Also included will be the amount of total commits and four and five stars for each team as well as average recruiting ranking which is the sum of a team’s national rank from the last five years divided by five.</p>
<p>247 does not provide an exact formula for its recruiting points, but clearly players are worth more points the higher their individual recruiting ranking. A team score of 70 or above would be considered elite and necessitates multiple four and five stars. Using average recruiting points provides a better indicator of recruiting strength as well as an actual score versus just the average of where a team ranked among other teams for average recruiting ranking.</p>
<pre class="r"><code>toprecruitteams %&gt;% 
  select(School, commits, fivestars, fourstars, avgrecruitingpts, avgrank) %&gt;%
  arrange(desc(avgrecruitingpts)) %&gt;%
  gt() %&gt;% 
  cols_label(
    School = &quot;School&quot;,
    commits = &quot;Commits&quot;,
    fivestars = &quot;Five Stars&quot;,
    fourstars = &quot;Four Stars&quot;,
    avgrecruitingpts = &quot;Average Recruiting Points&quot;,
    avgrank = &quot;Average Recruiting Rank&quot;
  ) %&gt;% 
  tab_header(
    title = &quot;Which teams have been the best at recruiting over the last five years?&quot;,
    subtitle = &quot;The bluebloods and historic powers still reign supreme on the recruiting trail.&quot;
  ) %&gt;% 
  tab_style(
    style = cell_text(color = &quot;black&quot;, weight = &quot;bold&quot;, align = &quot;left&quot;),
    locations = cells_title(&quot;title&quot;)
  ) %&gt;% 
  tab_style(
    style = cell_text(color = &quot;black&quot;, align = &quot;left&quot;),
    locations = cells_title(&quot;subtitle&quot;)
  ) %&gt;%
  tab_source_note(
    source_note = &quot;By Gavin Struve&quot;
  ) %&gt;%
  tab_source_note(
    source_note = md(&quot;Source: [247Sports](https://247sports.com/Season/2021-Basketball/CompositeTeamRankings/)&quot;)
  ) %&gt;% 
  tab_style(
    style = cell_text(color = &quot;black&quot;, weight = &quot;bold&quot;),
    locations = cells_body(
      columns = vars(School)
    )
  )  %&gt;%
  opt_row_striping() %&gt;% 
  opt_table_lines(&quot;none&quot;) %&gt;% 
  tab_style(
    style = cell_borders(sides = c(&quot;top&quot;, &quot;bottom&quot;), 
    color = &quot;grey&quot;, weight = px(1)),
    locations = cells_column_labels(everything())
  ) </code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#rbczyenhso .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: none;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rbczyenhso .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rbczyenhso .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rbczyenhso .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rbczyenhso .gt_bottom_border {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rbczyenhso .gt_col_headings {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rbczyenhso .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rbczyenhso .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rbczyenhso .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rbczyenhso .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rbczyenhso .gt_column_spanner {
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rbczyenhso .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#rbczyenhso .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rbczyenhso .gt_from_md > :first-child {
  margin-top: 0;
}

#rbczyenhso .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rbczyenhso .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: none;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rbczyenhso .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#rbczyenhso .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rbczyenhso .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#rbczyenhso .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rbczyenhso .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: none;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rbczyenhso .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rbczyenhso .gt_table_body {
  border-top-style: none;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rbczyenhso .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rbczyenhso .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#rbczyenhso .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rbczyenhso .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#rbczyenhso .gt_left {
  text-align: left;
}

#rbczyenhso .gt_center {
  text-align: center;
}

#rbczyenhso .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rbczyenhso .gt_font_normal {
  font-weight: normal;
}

#rbczyenhso .gt_font_bold {
  font-weight: bold;
}

#rbczyenhso .gt_font_italic {
  font-style: italic;
}

#rbczyenhso .gt_super {
  font-size: 65%;
}

#rbczyenhso .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="rbczyenhso" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal" style="color: black; text-align: left; font-weight: bold;">Which teams have been the best at recruiting over the last five years?</th>
    </tr>
    <tr>
      <th colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style="color: black; text-align: left;">The bluebloods and historic powers still reign supreme on the recruiting trail.</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">School</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Commits</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Five Stars</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Four Stars</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Average Recruiting Points</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" style="border-top-width: 1px; border-top-style: solid; border-top-color: grey; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: grey;">Average Recruiting Rank</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Duke</td>
      <td class="gt_row gt_right">26</td>
      <td class="gt_row gt_right">18</td>
      <td class="gt_row gt_right">8</td>
      <td class="gt_row gt_right">70.418</td>
      <td class="gt_row gt_right">1.8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Kentucky</td>
      <td class="gt_row gt_right gt_striped">29</td>
      <td class="gt_row gt_right gt_striped">20</td>
      <td class="gt_row gt_right gt_striped">9</td>
      <td class="gt_row gt_right gt_striped">70.306</td>
      <td class="gt_row gt_right gt_striped">1.8</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Arizona</td>
      <td class="gt_row gt_right">23</td>
      <td class="gt_row gt_right">6</td>
      <td class="gt_row gt_right">13</td>
      <td class="gt_row gt_right">65.866</td>
      <td class="gt_row gt_right">9.4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">North Carolina</td>
      <td class="gt_row gt_right gt_striped">21</td>
      <td class="gt_row gt_right gt_striped">8</td>
      <td class="gt_row gt_right gt_striped">9</td>
      <td class="gt_row gt_right gt_striped">64.314</td>
      <td class="gt_row gt_right gt_striped">11.4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Kansas</td>
      <td class="gt_row gt_right">20</td>
      <td class="gt_row gt_right">5</td>
      <td class="gt_row gt_right">9</td>
      <td class="gt_row gt_right">63.604</td>
      <td class="gt_row gt_right">13.4</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Oregon</td>
      <td class="gt_row gt_right gt_striped">22</td>
      <td class="gt_row gt_right gt_striped">5</td>
      <td class="gt_row gt_right gt_striped">14</td>
      <td class="gt_row gt_right gt_striped">62.388</td>
      <td class="gt_row gt_right gt_striped">17.6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Arizona State</td>
      <td class="gt_row gt_right">21</td>
      <td class="gt_row gt_right">1</td>
      <td class="gt_row gt_right">11</td>
      <td class="gt_row gt_right">60.046</td>
      <td class="gt_row gt_right">20.2</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">LSU</td>
      <td class="gt_row gt_right gt_striped">28</td>
      <td class="gt_row gt_right gt_striped">4</td>
      <td class="gt_row gt_right gt_striped">8</td>
      <td class="gt_row gt_right gt_striped">59.222</td>
      <td class="gt_row gt_right gt_striped">21.6</td>
    </tr>
    <tr>
      <td class="gt_row gt_left" style="color: black; font-weight: bold;">Alabama</td>
      <td class="gt_row gt_right">21</td>
      <td class="gt_row gt_right">1</td>
      <td class="gt_row gt_right">12</td>
      <td class="gt_row gt_right">59.000</td>
      <td class="gt_row gt_right">23.0</td>
    </tr>
    <tr>
      <td class="gt_row gt_left gt_striped" style="color: black; font-weight: bold;">Texas</td>
      <td class="gt_row gt_right gt_striped">18</td>
      <td class="gt_row gt_right gt_striped">4</td>
      <td class="gt_row gt_right gt_striped">13</td>
      <td class="gt_row gt_right gt_striped">58.808</td>
      <td class="gt_row gt_right gt_striped">27.6</td>
    </tr>
  </tbody>
  <tfoot class="gt_sourcenotes">
    <tr>
      <td class="gt_sourcenote" colspan="6">By Gavin Struve</td>
    </tr>
    <tr>
      <td class="gt_sourcenote" colspan="6">Source: <a href="https://247sports.com/Season/2021-Basketball/CompositeTeamRankings/">247Sports</a></td>
    </tr>
  </tfoot>
  
</table></div>
<p>From this table we can get a picture of which programs have excelled recruiting in recent years. Duke and Kentucky at the top are no surprise, neither are fellow powerhouses North Carolina and Kansas. Oregon has been the winningest team in the PAC 12 in this span over even Arizona, usually a perennial power, and Texas has money and prestige. Arizona State, LSU and Alabama are relative surprises however.</p>
<p>Now let’s examine how that recruiting prowess has translated to success. We’re going to use Kenpom ratings here for our success barometer. It gives an adjusted efficiency rating to each team that goes beyond win percentage by taking into account strength of schedule. This means power conference teams with losing records could be ranked above mid and low major teams with impressive records and winning percentages because of who they’ve played.</p>
<pre class="r"><code>ggplot() + 
  geom_point(data=recruitingtables, aes(x=avgrecruitingpts, y=kenpom)) +
    geom_smooth(data=recruitingtables, aes(x=avgrecruitingpts, y=kenpom), method=&quot;lm&quot;) +
    geom_text_repel(data=toprecruitteams, aes(x=avgrecruitingpts, y=kenpom, label=School)) +
  labs(x=&quot;Average Recruiting Points&quot;, y=&quot;Average adjusted efficiency rating&quot;, title=&quot;How do the top recruiting teams rate on the court? &quot;, subtitle=&quot;It&#39;s evident that elite recruiting does not ensure grand success.&quot;, caption=&quot;Source: Sports Reference &amp; 247Sports | By Gavin Struve&quot;) +
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    axis.title = element_text(size = 10),
    axis.text = element_text(size = 7),
    axis.ticks = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )</code></pre>
<p><img src="http://gavinstruve.github.io/post/2021/04/25/how-much-does-recruiting-impact-success-and-vice-versa-in-college-basketball/index_files/figure-html/unnamed-chunk-5-1.png" width="672" />
An efficiency rating above a zero essentially means you’re above average, which every power conference team is over the five-year period. A rating of 20 or above indicates around a top-20 team in a season and a rating of 30 indicates a title contender or elite team. To sustain either level over a multi-year span puts you in elite company.</p>
<p>The added line directly shows who is overachieving and underachieving relative to their recruiting product. Kansas and Duke have translated their top recruiting classes into being among the top few on-court teams while schools like Kentucky, North Carolina and Oregon aren’t far behind. Contrary to popular belief, Texas actually hasn’t been as disappointing as some of its recruiting peers, rating as right above the kenpom bubble team standard on average along with Arizona. SEC football schools LSU and Alabama have fared worse with their top recruiting classes, and Arizona State has struggled to put forth a competent power conference product despite its fruitful recruiting efforts.</p>
<pre class="r"><code>topteams &lt;- recruitingtables %&gt;% filter(fiveyrwinperc &gt; 0.73)
bottomteams &lt;- recruitingtables %&gt;% filter(fiveyrwinperc &lt; 0.45)</code></pre>
<pre class="r"><code>ggplot() + 
  geom_point(data=recruitingtables, aes(x=avgrecruitingpts, y=fiveyrwinperc, size=kenpom), 
    color=&quot;grey&quot;, 
    alpha=.5) +
  geom_point(data=topteams, aes(x=avgrecruitingpts, y=fiveyrwinperc, size=kenpom), 
    color=&quot;green&quot;)+
    geom_point(data=bottomteams, aes(x=avgrecruitingpts, y=fiveyrwinperc, size=kenpom), 
    color=&quot;red&quot;)+
      geom_text_repel(data=topteams, aes(x=avgrecruitingpts, y=fiveyrwinperc, label=School)) +
   geom_text_repel(data=bottomteams, aes(x=avgrecruitingpts, y=fiveyrwinperc, label=School)) +
  labs(x=&quot;Average Recruiting Points&quot;, y=&quot;Win-Loss Percentage&quot;, title=&quot;How much does free throw shooting affect game outcome?&quot;, subtitle=&quot;The top free throw shooting teams would indicate there is some correlation.&quot;, caption=&quot;Source: Sports Reference &amp; 247Sports | By Gavin Struve&quot;) +
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 16, face = &quot;bold&quot;),
    axis.title = element_text(size = 10),
    axis.text = element_text(size = 7),
    axis.ticks = element_blank(),
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank()
  )</code></pre>
<p><img src="http://gavinstruve.github.io/post/2021/04/25/how-much-does-recruiting-impact-success-and-vice-versa-in-college-basketball/index_files/figure-html/unnamed-chunk-7-1.png" width="672" />
This bubble chart also provides breakdown of how a team’s average recruiting points intersected with its win loss percentage. Additionally, their average kenpom rating determines the size of the bubble. We have the best and worst teams labeled by filtering them out. We used a 73% winning percentage as the cutoff for the top teams because it provides a picture of the top ten-or-so teams without overwhelming the eye. The cutoff for the bottom teams is 45% for similar reasons, California and Vanderbilt overlap due to their close proximity in both axis measures and can’t be removed without taking out several other teams.</p>
<p>Breaking down this chart, we can come to a myriad of conclusions. What pops out first is that Gonzaga has won over 90% of its games in the past five seasons with an amount average recruiting points compared to power conference teams. Houston is near 80% with a bottom-quarter recruiting ranking, and Wichita State is at a similar level.</p>
<p>This season’s national champion, Baylor, has won nearly three-quarters of its games at a worse-than-average recruiting level. Looking at the worst teams, none of the bottom nine in winning percentage were among or close to the top recruiters. We can see a greater difference in size by kenpom weight. California and Washington State have similar winning percentages to Nebraska and Northwestern but noticeably worse adjusted efficiency ratings. Perhaps this gives less credence to the idea that the PAC 12 is comparable to the Big Ten after a far worse regular season but far better NCAA Tournament showing leaguewide.</p>
<pre class="r"><code>twentyonerecruits &lt;- thisyrrecruits %&gt;% rename(&quot;avgrank&quot; = &quot;Avg. Rank&quot;)</code></pre>
<pre class="r"><code>ggplot() + 
  geom_dumbbell(
    data=twentyonerecruits, 
    aes(y=School, x=Rank, xend=avgrank),
    colour = &quot;black&quot;,
    colour_x = &quot;blue&quot;,
    colour_xend = &quot;red&quot;)+
   labs(
    x=&quot;Recruiting Rank&quot;, 
    y=&quot;Team&quot;, 
    title=&quot;How have 2021&#39;s top recruiting teams previously fared?&quot;,
    subtitle=&quot;Most of 2021&#39;s top recruiting teams had marked improvements in recruiting this year.&quot;,
    caption=&quot;Source: 247Sports | By Gavin Struve&quot;) +
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 14.5, face = &quot;bold&quot;),
    axis.title = element_text(size = 10),
   )</code></pre>
<p><img src="http://gavinstruve.github.io/post/2021/04/25/how-much-does-recruiting-impact-success-and-vice-versa-in-college-basketball/index_files/figure-html/unnamed-chunk-9-1.png" width="672" />
To finish looking forward, we have a dumbbell chart showing the change in average recruiting rank to recruiting rank this year for 2021’s top 25 recruiting teams as the recruiting period is about over. We can see almost everyone saw a huge improvement from their five-year average to 2021, highlighted by new No. 1 and 2 Michigan and Gonzaga. Only recruiting powerhouses Duke and Kentucky had worse classes by their standards.</p>
<pre class="r"><code>fit &lt;- lm(fiveyrwinperc ~ avgrecruitingpts, data = recruitingtables)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = fiveyrwinperc ~ avgrecruitingpts, data = recruitingtables)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.215308 -0.069520 -0.002353  0.065855  0.305438 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      0.393560   0.067790   5.806 1.21e-07 ***
## avgrecruitingpts 0.004270   0.001373   3.110  0.00258 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1061 on 81 degrees of freedom
##   (10 observations deleted due to missingness)
## Multiple R-squared:  0.1067, Adjusted R-squared:  0.09566 
## F-statistic: 9.674 on 1 and 81 DF,  p-value: 0.00258</code></pre>
<pre class="r"><code>fit &lt;- lm(kenpom ~ avgrecruitingpts, data = recruitingtables)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = kenpom ~ avgrecruitingpts, data = recruitingtables)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -11.1759  -3.3315   0.3158   3.4203  14.9389 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       0.11289    3.39412   0.033    0.974    
## avgrecruitingpts  0.29278    0.06874   4.259 5.49e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.311 on 81 degrees of freedom
##   (10 observations deleted due to missingness)
## Multiple R-squared:  0.183,  Adjusted R-squared:  0.1729 
## F-statistic: 18.14 on 1 and 81 DF,  p-value: 5.495e-05</code></pre>
<p>These linear models give a number to this speculation. The r-squared at the bottom of the first model is 0.09566 which indicates that a team’s average recruiting points can predict about 9.5% of the variance in win percentage, the low p-value, below the standard of 0.05, indicates that this is statistically significant. The second linear model indicates that a team’s average recruiting points accounts for 17.29% of the variance in Kenpom adjusted efficiency rating, and it has a very low p-value indicating it is extremely statistically significant. This is part of why I gave a little more credence to adjusted efficiency rating in its relationship to recruiting level. I also ran a linear model (not pictured to save space) for the correlation between win percentage and kenpom adjusted efficiency rating, and it said they’re about an 81% predictor of each other.</p>
<p>There are many other variables that this data can’t account for that help determine how good a team is like transfers, player development and retention. Often Duke and Kentucky recruit so well that their high-profile players leave after one season which may not benefit them as much as the average four-star who stays four years. What we can see is that recruiting success, average recruiting points in particular, are one of the key indicators for team success. Recruiting well is no guarantee that you’ll win games, but teams like national finalists Baylor and Gonzaga have shown that mediocre recruiting is no excuse for mediocre on-court results. Now they’re reaping the benefits with all-time recruiting classes.</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js//highlight.min.js"></script>



<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
  </body>
</html>

